'use client'

import { usePathname } from 'next/navigation'
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/page";



// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = usePathname();

  return (
    <html lang="en">
      <body >
        {router !== '/login' && router !== "/register"  && router !== "/"  && <Navbar />}
        {children}
      </body>
    </html>
  );
}
